# ========== SERVER ==========
server.port=8082

# ========== DATASOURCE (MySQL) ==========
spring.datasource.url=jdbc:mysql://localhost:3306/notificationdb?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=tamnhu13

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ========== MAIL (SMTP) ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luongtamnhu102hht@gmail.com
spring.mail.password=jaaqiqpbrorczmfm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
