spring.application.name=Eventix
server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable data.sql for now - will use programmatic data initialization
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

# OpenAPI UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Thư mục lưu QR 
eventix.qr.dir=qr_codes


momo.partnerCode=MOMO
momo.accessKey=your_access_key
momo.secretKey=your_secret_key
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.returnUrl=http://localhost:8080/api/payments/return
momo.notifyUrl=http://localhost:8080/api/payments/notify

spring.profiles.active=db
# RabbitMQ configuration (connect to checkin service)
spring.rabbitmq.host=100.72.224.90
spring.rabbitmq.port=5672
spring.rabbitmq.username=eventix
spring.rabbitmq.password=password
spring.rabbitmq.virtual-host=/